don't pollute the environment with AWS_* variables if sts fails

diff --git a/assume-role b/assume-role
--- a/assume-role
+++ b/assume-role
@@ -317,12 +317,6 @@ assume-role-with-bastion() {
     AWS_SESSION_SECURITY_TOKEN=$AWS_SESSION_SESSION_TOKEN
   fi
 
-  # Use the Session in the login account
-  export AWS_ACCESS_KEY_ID=$AWS_SESSION_ACCESS_KEY_ID
-  export AWS_SECRET_ACCESS_KEY=$AWS_SESSION_SECRET_ACCESS_KEY
-  export AWS_SESSION_TOKEN=$AWS_SESSION_SESSION_TOKEN
-  export AWS_SECURITY_TOKEN=$AWS_SESSION_SECURITY_TOKEN
-
   ROLE_SESSION_START=$NOW
 
   # Now drop into a role using session token's long-lived MFA
@@ -331,7 +325,12 @@ assume-role-with-bastion() {
   ROLE_SESSION_ARGS+=(--duration-seconds "${ROLE_SESSION_TIMEOUT}")
   ROLE_SESSION_ARGS+=(--role-session-name "$(date +%s)")
 
-  ROLE_SESSION=$(aws sts assume-role "${ROLE_SESSION_ARGS[@]}" || echo "fail")
+  # Use the Session in the login account
+  ROLE_SESSION=$(AWS_ACCESS_KEY_ID="$AWS_SESSION_ACCESS_KEY_ID" \
+                 AWS_SECRET_ACCESS_KEY="$AWS_SESSION_SECRET_ACCESS_KEY" \
+                 AWS_SESSION_TOKEN="$AWS_SESSION_SESSION_TOKEN" \
+                 AWS_SECURITY_TOKEN="$AWS_SESSION_SECURITY_TOKEN" \
+                 aws sts assume-role "${ROLE_SESSION_ARGS[@]}" || echo "fail")
 }
 
 export-envars() {
