Add default profile option for when .aws/credentials does not necesarily map to default

diff --git a/assume-role b/assume-role
--- a/assume-role
+++ b/assume-role
@@ -47,6 +47,7 @@ assume-role(){
   #######
 
   # exports
+  export AWS_DEFAULT_PROFILE_ASSUME_ROLE
   export AWS_SESSION_START
   export AWS_SESSION_ACCESS_KEY_ID
   export AWS_SESSION_SECRET_ACCESS_KEY
@@ -80,6 +81,15 @@ assume-role(){
   #######
   # SETUP
   #######
+
+  # load default assume-role profile if available, use "default" otherwise
+  if [ -z "$AWS_DEFAULT_PROFILE_ASSUME_ROLE" ]; then
+    echo -n "Using default assume role (awscli) profile from environment variable"
+    default_profile=${AWS_DEFAULT_PROFILE_ASSUME_ROLE:-"default"}
+  fi
+
+  # XXX
+  default_profile="prod"
 
   # set account_name
   if [ -z "$account_name_input" ] && [ -z "$OUTPUT_TO_EVAL" ]; then
@@ -173,13 +183,13 @@ assume-role(){
     fi
 
     # get the username attached to your default creds
-    AWS_USERNAME=$(aws iam get-user --query User.UserName --output text)
+    AWS_USERNAME=$(aws iam get-user --query User.UserName --output text --profile $default_profile)
 
     # get MFA device attached to default creds
     MFA_DEVICE_ARGS=(--user-name $AWS_USERNAME)
     MFA_DEVICE_ARGS+=(--query 'MFADevices[0].SerialNumber')
     MFA_DEVICE_ARGS+=(--output text)
-    MFA_DEVICE=$(aws iam list-mfa-devices "${MFA_DEVICE_ARGS[@]}")
+    MFA_DEVICE=$(aws iam list-mfa-devices "${MFA_DEVICE_ARGS[@]}" --profile $default_profile)
     MFA_DEVICE_STATUS=$?
 
     if [ $MFA_DEVICE_STATUS -ne 0 ]; then
@@ -191,7 +201,7 @@ assume-role(){
     SESSION_ARGS=(--duration-seconds $SESSION_TIMEOUT)
     SESSION_ARGS+=(--serial-number ${MFA_DEVICE})
     SESSION_ARGS+=(--token-code ${mfa_token})
-    SESSION=$(aws sts get-session-token "${SESSION_ARGS[@]}")
+    SESSION=$(aws sts get-session-token "${SESSION_ARGS[@]}" --profile $default_profile)
     SESSION_STATUS=$?
 
     if [ $SESSION_STATUS -ne 0 ]; then
@@ -216,7 +226,7 @@ assume-role(){
   ROLE_SESSION_ARGS+=(--external-id ${account_id})
   ROLE_SESSION_ARGS+=(--duration-seconds ${ROLE_SESSION_TIMEOUT})
   ROLE_SESSION_ARGS+=(--role-session-name $(date +%s))
-  ROLE_SESSION=$(aws sts assume-role "${ROLE_SESSION_ARGS[@]}" || echo "fail")
+  ROLE_SESSION=$(aws sts assume-role "${ROLE_SESSION_ARGS[@]} --profile $default_profile" || echo "fail")
 
   if [ "$ROLE_SESSION" = "fail" ]; then
      echo_out "Failed to export session envars."
@@ -235,6 +245,7 @@ assume-role(){
 
   # OUTPUTS ALL THE EXPORTS for eval $(assume-role [args])
   if [ "$OUTPUT_TO_EVAL" = "true" ]; then
+    echo "export AWS_DEFAULT_PROFILE_ASSUME_ROLE=\"$AWS_DEFAULT_PROFILE_ASSUME_ROLE\";"
     echo "export AWS_REGION=\"$AWS_REGION\";"
     echo "export AWS_DEFAULT_REGION=\"$AWS_DEFAULT_REGION\";"
     echo "export AWS_ACCESS_KEY_ID=\"$AWS_ACCESS_KEY_ID\";"
